### PR TITLE
allow not to verify ssl

### PR DESCRIPTION
**Pull request by syphar**

### CODE REVIEW

**Comment by samifahed** [comment]
@syphar tests fail

**Comment by samifahed** [comment]
and honestly I would rather have it verify with the missing ssl certificate than not verify at all

**Comment by syphar** [comment]
@samifahed hmm... it's optional and default activated ... to me it feels ok to disable it temporarily until they have fixed it. 

But on the other side, it would be more secure.

**Comment by codingjoe** [comment]
API change is a minor release, not a fix ;)

**Pull request closed without merging**
